spring:  
# datasource: 
#  driver-class-name: org.postgresql.Driver
#  url: jdbc:postgresql://localhost:5432/demo_db
#  username: admin
#  password: admin
# liquibase:
#  change-log: classpath:db/changelog/db.changelog-master.xml
#  enabled: true
#  drop-first: false
#  url: jdbc:postgresql://localhost:5432/demo_db
#  user: admin
#  password: admin
#  driverClassName: org.postgresql.Driver
#  clearCheckSums: true
 datasource:
  url: jdbc:h2:mem:demodb
  username: sa
  password: password
  driverClassName: org.h2.Driver
 jpa:
  spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  hibernate.ddl-auto: update
  show-sql: true
 
  
server:
 port: 8086
 