spring:
 profiles:
  active: dev
 cloud:
  config:
   enabled: false
# autoconfigure: 
#  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
   
fixerapi:
 latest-url: http://api.exchangeratesapi.io/v1/latest?access_key=39ced528747371cbf637cb201033f86d&symbols=



